from __future__ import annotations

from enum import StrEnum


class OrderState(StrEnum):
    NEW_SIGNAL = "NEW_SIGNAL"
    AI_REVIEWED = "AI_REVIEWED"
    RISK_APPROVED = "RISK_APPROVED"
    RISK_REJECTED = "RISK_REJECTED"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    CANCELED = "CANCELED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"
    FAILED = "FAILED"
    DRY_RUN_APPROVED = "DRY_RUN_APPROVED"
    DRY_RUN_REJECTED = "DRY_RUN_REJECTED"
    WAITING_USER_STREAM = "WAITING_USER_STREAM"
    RECONCILED = "RECONCILED"
    RECONCILIATION_FAILED = "RECONCILIATION_FAILED"


BINANCE_STATUS_TO_ORDER_STATE = {
    "NEW": OrderState.WAITING_USER_STREAM,
    "PARTIALLY_FILLED": OrderState.PARTIALLY_FILLED,
    "FILLED": OrderState.FILLED,
    "CANCELED": OrderState.CANCELED,
    "REJECTED": OrderState.REJECTED,
    "EXPIRED": OrderState.EXPIRED,
}
